name = "EvesGarden"
author = "Dr4kiam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9218fde8e0718d399575279c063a509b21fc36d1e24c96f3c61595f70976b45f"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
