name = "EvesGarden"
author = "Dr4kiam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20feb6ae69c46ba5d59212574c6b85b7c4c168122c16d06e95360eecc78015cc"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
