name = "EvesGarden"
author = "Dr4kiam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d9de40719807b707afb4a80a0d7b6b35e5fdc28254bc1d1019d1b2777c81f65"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
